// Copyright (C) 2019 by Joseph Mirabel, LAAS-CNRS.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
// notice, this list of conditions and the following disclaimer in the
// documentation and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
// DAMAGE.

#ifndef HPP_MANIPULATION_CORBA_PROBLEM_IDL
#define HPP_MANIPULATION_CORBA_PROBLEM_IDL
#include <hpp/core_idl/_problem.idl>

module hpp
{
  module core_idl {
    interface Problem;
  }; // module core
  
  module manipulation_idl {
    module graph_idl {
      interface Graph;
    };

    interface Problem : core_idl::Problem
    {
      graph_idl::Graph getConstraintGraph () raises (Error);
      //-> constraintGraph
    }; // interface Problem

  }; // module core
}; // module hpp

//* #include <hpp/core_idl/_problem.hh>
//* #include <hpp/manipulation_idl/_graph.hh>
//* #include <hpp/manipulation/problem.hh>
//* #include <hpp/manipulation/steering-method/graph.hh>
//* #include <hpp/manipulation/graph-path-validation.hh>

#include <hpp/manipulation_idl/_graph.idl>

#endif // HPP_MANIPULATION_CORBA_PROBLEM_IDL
